name: Check pull request labels

on:
    pull_request:
        types: [opened, labeled, unlabeled]
    merge_group:

jobs:
    check-labels:
        runs-on: ubuntu-latest
        if: >
            github.event_name == 'merge_group' ||
            (
                contains(github.event.pull_request.labels.*.name, 'breaking') == false &&
                contains(github.event.pull_request.labels.*.name, 'bug') == false &&
                contains(github.event.pull_request.labels.*.name, 'feature') == false &&
                contains(github.event.pull_request.labels.*.name, 'enhancement') == false &&
                contains(github.event.pull_request.labels.*.name, 'documentation') == false &&
                contains(github.event.pull_request.labels.*.name, 'upgrade') == false &&
                contains(github.event.pull_request.labels.*.name, 'refactor') == false &&
                contains(github.event.pull_request.labels.*.name, 'build') == false
            )
        steps:
            - name: Accept queued merge group
              if: github.event_name == 'merge_group'
              run: echo "Pull request labels were checked before entering the merge queue"
            - name: Reject unlabeled pull request
              if: github.event_name == 'pull_request'
              run: echo "None of the required pull request labels are set" && exit 1
